# Generated by Django 4.2.5 on 2023-11-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumble_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
